SHULTSEDU-280-SQLite-DB
nadiiazhurba/Combined-Shell-TestProject pull request #11
Opened 2020-11-02 15:59 UTC by nadiiazhurba

2020-11-03 07:28 UTC, YuliaLoyko requested changes

2020-11-03 07:28 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Database/Repositories/ContactRepository.cs
> +        protected override string DatabasePath => Constants.Database.ContactsDatabasePath;
do we need a separate DB path for each repository?

2020-11-03 07:28 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> -            Contacts = ContactsData.ContactsModels;
we can remove hardcoded values

2020-11-03 07:30 UTC, YuliaLoyko requested changes

2020-11-03 07:30 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Database/Interfaces/IRepository.cs
> +    public interface IRepository<T>
add doc comments please)

2020-11-03 09:35 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> -            Contacts = ContactsData.ContactsModels;
I thought about leaving it as a mock for testing. But sure, I can delete it. Will provide it in next commit.

2020-11-03 09:38 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Repositories/ContactRepository.cs
> +        protected override string DatabasePath => Constants.Database.ContactsDatabasePath;
We don't need it, but we can use it this way. If it's more convenient in case of implementation which you have in mind further, I can change this to just 1 DB for the whole project with this in mind.
I'll provide it in next commit.

2020-11-03 09:43 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Interfaces/IRepository.cs
> +    public interface IRepository<T>
Done it

2020-11-04 06:26 UTC, YuliaLoyko approved these changes

2020-11-04 08:18 UTC, merged