Shultsedu 286 localization
nadiiazhurba/Combined-Shell-TestProject pull request #13
Opened 2020-11-04 09:51 UTC by nadiiazhurba

2020-11-05 14:04 UTC, YuliaLoyko requested changes
i actually thought that we're going to implement localization, which is not just moving strings to resx files, but provide the mechanism of translation?

2020-11-05 14:13 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.iOS/Info.plist
> -    <key>UIDeviceFamily</key>
It is the issue with it that appears after opening in different IDEs. I'm trying not to change it on purpose.

2020-11-05 14:16 UTC, nadiiazhurba commented
> actually thought that we're going to implement localization, which is not just moving strings to resx files, but provide the mechanism of translation?

Actually, from now on localization should work by itself. If I add more files with another languages and user have different language settings he should see app in it's preferred local. And also with each new resx file I should add language in info.plist.

2020-11-05 14:20 UTC, nadiiazhurba commented
I believe that we haven't discussed earlier such changes as a mechanism of language changes if you mean something like new Settings page with possibilities to switch between different locales. Only adding strings to resources. Which, actually means adding possibility to extend application with new locales.

2020-11-06 15:28 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject.iOS/Info.plist
> -    <key>UIDeviceFamily</key>
so don't commit if no actual change)

2020-11-06 15:30 UTC, YuliaLoyko commented
> > actually thought that we're going to implement localization, which is not just moving strings to resx files, but provide the mechanism of translation?
> 
> Actually, from now on localization should work by itself. If I add more files with another languages and user have different language settings he should see app in it's preferred local. And also with each new resx file I should add language in info.plist.

so let's add another files for different locales) you can translate just a couple of strings - to show that it works

2020-11-06 15:36 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.iOS/Info.plist
> -    <key>UIDeviceFamily</key>
There was an actual change. I've added preferred locale for an iOS app, as it was suggested in tutorial. Lines 37-38. I'm sorry that I haven't written it earlier, so you wouldn't have to check the difference by yourself.

<key>CFBundleDevelopmentRegion</key>
	<string>en</string>

2020-11-06 15:38 UTC, nadiiazhurba commented
> > > actually thought that we're going to implement localization, which is not just moving strings to resx files, but provide the mechanism of translation?
> > 
> > 
> > Actually, from now on localization should work by itself. If I add more files with another languages and user have different language settings he should see app in it's preferred local. And also with each new resx file I should add language in info.plist.
> 
> so let's add another files for different locales) you can translate just a couple of strings - to show that it works

Sure, no problem. I'll do it.

2020-11-09 07:22 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject.iOS/Info.plist
> -    <key>UIDeviceFamily</key>
so commit only actual change)

2020-11-09 09:35 UTC, nadiiazhurba commented
> > > > actually thought that we're going to implement localization, which is not just moving strings to resx files, but provide the mechanism of translation?
> > > 
> > > 
> > > Actually, from now on localization should work by itself. If I add more files with another languages and user have different language settings he should see app in it's preferred local. And also with each new resx file I should add language in info.plist.
> > 
> > 
> > so let's add another files for different locales) you can translate just a couple of strings - to show that it works
> 
> Sure, no problem. I'll do it.

Done it

2020-11-10 10:47 UTC, YuliaLoyko approved these changes

2020-11-10 10:48 UTC, merged