Shultsedu 287 map location tracking
nadiiazhurba/Combined-Shell-TestProject pull request #16
Opened 2020-11-06 11:54 UTC by nadiiazhurba

2020-11-06 15:45 UTC, YuliaLoyko requested changes

2020-11-06 15:45 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +    public class PinLocation : INotifyPropertyChanged
any specific reason of implementing this interface here instead of extending BindableObject and using SetProperty?)

2020-11-06 15:45 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Services/GeolocationService/IGeolocationService.cs
> +    public interface IGeolocationService
no doc comments in public interfaces again)

2020-11-06 15:45 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Views/MapPage.xaml.cs
> +            ((MapPageViewModel)BindingContext).OnAppearing();
may be let's think about moving OnAppearing to all viewModels? it might be helpful

2020-11-06 15:53 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +    public class PinLocation : INotifyPropertyChanged
Yes, it is. It's because I'm binding specifically fields from this class and Map should track them for updates, not only their Collection.

2020-11-06 16:00 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Services/GeolocationService/IGeolocationService.cs
> +    public interface IGeolocationService
Oops, my bad. I was totally distracted by the code and somehow StyleCop didn't remind me about that:( Already pushing to brunch commit that fixes it. I usually don't make same mistakes more than once, but this habit somehow not the easy to get for me.

2020-11-06 16:01 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/MapPage.xaml.cs
> +            ((MapPageViewModel)BindingContext).OnAppearing();
Good idea. I'll do it right away and will push it in the next commit.

2020-11-09 09:38 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Services/GeolocationService/IGeolocationService.cs
> +    public interface IGeolocationService
Done it

2020-11-09 09:38 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/MapPage.xaml.cs
> +            ((MapPageViewModel)BindingContext).OnAppearing();
Done it

2020-11-10 10:55 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +    public class PinLocation : INotifyPropertyChanged
so still not fully clear, why we don't use ExtendedBindableObject?

2020-11-10 11:04 UTC, YuliaLoyko requested changes

2020-11-10 11:04 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Views/MapPage.xaml.cs
> +            MessagingCenter.Subscribe<MapPageViewModel, string>(this, "Alert", async (sender, message) =>
let's reduce dependencies
so usually it does not matter, which page or service sent us message. so we can subscribe to a specific event (eg create a new class). it can also contain both message const

2020-11-10 11:04 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/MapPageViewModel.cs
> +            MessagingCenter.Send(this, "Alert", displayMessage);
let's not hardcode strings in multiple places)

2020-11-11 14:07 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +    public class PinLocation : INotifyPropertyChanged
Now I understand what you mean. Done it.

2020-11-11 16:26 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/MapPage.xaml.cs
> +            MessagingCenter.Subscribe<MapPageViewModel, string>(this, "Alert", async (sender, message) =>
Done it

2020-11-11 16:26 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/MapPageViewModel.cs
> +            MessagingCenter.Send(this, "Alert", displayMessage);
Done it

2020-11-12 07:34 UTC, YuliaLoyko requested changes
i'll finish a review when merge conflicts are resolved)

2020-11-12 07:34 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +                if (!position.Equals(value))
i think we do the equality check in SetProperty method. do we need to do it here?

2020-11-12 09:05 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +                if (!position.Equals(value))
Yeap, forgot. Done it.

2020-11-12 09:20 UTC, YuliaLoyko approved these changes

2020-11-12 09:23 UTC, merged