Shultsedu 287 map location tracking background
nadiiazhurba/Combined-Shell-TestProject pull request #17
Opened 2020-11-10 10:43 UTC by nadiiazhurba

2020-11-10 11:13 UTC, YuliaLoyko requested changes

2020-11-10 11:13 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject.Android/Services/GeolocationService/LocationService.cs
> +            MessagingCenter.Send(this, "StartTrackingLocation", action);
let's not hardcode strings)

2020-11-10 11:13 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject.iOS/AppDelegate.cs
> +        public override void OnActivated(UIApplication uiApplication)
could you please check this article (and may some others) about background modes for iOS?
let's implement system background mode)
 https://developer.apple.com/documentation/corelocation/getting_the_user_s_location/handling_location_events_in_the_background

2020-11-12 10:08 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.Android/Services/GeolocationService/LocationService.cs
> +            MessagingCenter.Send(this, "StartTrackingLocation", action);
Done it

2020-11-13 08:10 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject.iOS/AppDelegate.cs
> +        public override void OnActivated(UIApplication uiApplication)
so did you add location background mode? i don't see changes in info.plist

2020-11-13 08:57 UTC, YuliaLoyko approved these changes

2020-11-13 08:57 UTC, merged