Shultsedu 295 analytics
nadiiazhurba/Combined-Shell-TestProject pull request #19
Opened 2020-11-18 16:03 UTC by nadiiazhurba

2020-11-19 07:37 UTC, YuliaLoyko requested changes

2020-11-19 07:37 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject.Android/SideMenuFlyoutShellTestProject.Android.csproj
> +    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
did you try to create custom profile?

2020-11-19 07:37 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return null;
i'd return null result instead of null task

2020-11-19 07:37 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return Database.Table<T>().ToListAsync();
and actually exception might never been catched when you're returning task

2020-11-19 07:37 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +        private void SetProperty<T>(
can we handle it by a default interface implementation?

2020-11-19 08:22 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.Android/SideMenuFlyoutShellTestProject.Android.csproj
> +    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
No, I didn't. I've just used default one.

2020-11-19 08:30 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return null;
Now, that I re-think about it, I would trow exception further in order not to interrupt exception flow on this stage. In order to track error, but to be able in some future to handle it showing some user-friendly error. If these issues are going to happen normally, of course.

2020-11-19 08:30 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return null;
Done it

2020-11-19 08:41 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return Database.Table<T>().ToListAsync();
If I understand it correctly, they might not be catched in case if the method call, which throws, is not awaited. Each of the methods used inside are awaited and then these methods are awaited as well. 
But if it's still considered to be not a good technique I can change it by your suggestion of where these catches would fit better.

2020-11-19 08:46 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +        private void SetProperty<T>(
Unfortunately not. This model can't inherit from both classes BaseEntity and ExtendedBindableObject, they have different purposes and both needed for this class, so in one of the cases I should have used only interface.

2020-11-20 12:07 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject.Android/SideMenuFlyoutShellTestProject.Android.csproj
> +    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
let's try)

2020-11-20 12:10 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return Database.Table<T>().ToListAsync();
but method inside try is not awaited) it just returns task. so if task is running eg for 3 sec and then throws - it will be moved out of try block before exception is thrown here

2020-11-20 12:10 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +        private void SetProperty<T>(
yes, that's why i'm saying default interface implementation
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods

2020-11-20 12:12 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return null;
let's add doc comments and describe this behaviour here

2020-11-20 12:13 UTC, YuliaLoyko requested changes
please, see my responses to comments

2020-11-20 14:39 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.Android/SideMenuFlyoutShellTestProject.Android.csproj
> +    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
Done it)

2020-11-20 14:48 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return Database.Table<T>().ToListAsync();
I see, agree with you. Thanks for this comment. Awaited this method.

2020-11-20 15:01 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return null;
Added doc comments.

2020-11-20 22:31 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +        private void SetProperty<T>(
That's a really interesting suggestion. In order to learn and get use of it, I've tried, but there is still small issue left. Methods are only available on the interface, not the class and if I try to use methods from interface, I should call them directly from interface. For example, like this: 

`set => ((IExtendedBindableObject)this).SetProperty(ref position, value);`

And also I have to update netstandard version to latest one and Xamarin as well, because all app seems to be broken after netstandard upgrade. 
I can continue investigating this if you think it's worthy to make such a big changes for that.

2020-11-23 07:35 UTC, YuliaLoyko requested changes

2020-11-23 07:35 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject.iOS/SideMenuFlyoutShellTestProject.iOS.csproj
> +    <CodesignProvision>VS: WildCard Development</CodesignProvision>
do we need a provision for simulator configuration?

2020-11-23 07:35 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return Database.GetAsync<T>(id);
await?

2020-11-23 07:35 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                    return Database.DeleteAsync<T>(id);
await?

2020-11-23 07:35 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +        private void SetProperty<T>(
that's fine with calling methods from interface (we can this about some property, which will return interface)
regading netstandard - i'm not pretty sure, why do you need to update it? it's just a language version

2020-11-23 08:13 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +        private void SetProperty<T>(
I've tried to find the truly reason for this issue thinking that it's the JetBrains Rider bug, because of which I should change the version of nestandard to 2.1. https://youtrack.jetbrains.com/issue/RSRP-474628
But VS won't compile without implicit implementation as well, so I found this specification which tells that only netstandard 2.1 supports C# 8.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

.NET Standard | 2.1 | C# 8.0

2020-11-23 12:29 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Models/PinLocation.cs
> +        private void SetProperty<T>(
But, after all, with some time of investigations, I managed to do it.
Done!

2020-11-23 12:32 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                    return Database.DeleteAsync<T>(id);
It is already synced because it uses Locker.

2020-11-23 12:33 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                return Database.GetAsync<T>(id);
Done it

2020-11-23 12:38 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.iOS/SideMenuFlyoutShellTestProject.iOS.csproj
> +    <CodesignProvision>VS: WildCard Development</CodesignProvision>
I probably could be done accidentally after release. Changed it

2020-11-23 12:39 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.iOS/SideMenuFlyoutShellTestProject.iOS.csproj
> +    <CodesignProvision>VS: WildCard Development</CodesignProvision>
Changed it

2020-11-23 13:02 UTC, YuliaLoyko requested changes

2020-11-23 14:13 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Database/Base/BaseRepository.cs
> +                    return Database.DeleteAsync<T>(id);
Good idea. Done it

2020-11-23 14:21 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +        private async void DeleteContactItem(Contact item)
Ok. It took some changes for method call for Commands, but nothing special. Done it

2020-11-23 15:11 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.iOS/SideMenuFlyoutShellTestProject.iOS.csproj
> +    <LangVersion>8.0</LangVersion>
Agree, changed that. Is it right now?

2020-11-23 15:19 UTC, YuliaLoyko approved these changes

2020-11-23 16:03 UTC, merged