Shultsedu 255 add dic
nadiiazhurba/Combined-Shell-TestProject pull request #3
Opened 2020-10-13 16:19 UTC by nadiiazhurba

2020-10-14 10:06 UTC, YuliaLoyko requested changes

2020-10-14 10:06 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/BasePrinciplePageViewModel.cs
> +        private Principle _model;
we also use a little bit another file structure:
all fields 
consttructor
all properties
all methods

and inside the groups: 
public
proteced
private

2020-10-14 10:06 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/AppShell.xaml.cs
> +            sPrinciplePage.Title = sPrinciplePage.ViewModel.Model.Title;
may be it's worth just binding the title?

2020-10-14 10:06 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/App.xaml.cs
> +            Container.Collection.Register(typeof(IViewModel<>), asm);
i'm a little bit confused with registering both interfaces and concrete viewModels. why would we need both?

2020-10-15 07:39 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/BasePrinciplePageViewModel.cs
> +        private Principle _model;
Re-done order in all of the files.

2020-10-15 07:39 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/PrincipleInfoPage.xaml.cs
> +    public partial class PrincipleInfoPage : IView<Principle>
Done it. Added base class for all pages.
And base ViewModel as well

2020-10-15 07:39 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/PrincipleInfoPage.xaml
> +                         Padding="30,0,30,24"
Done. Added spaces for all Margins and Paddings.

2020-10-15 07:39 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/DetailsPage.xaml.cs
> +        private string _prevTitle;
Ok, I see. Renamed all local fields removing underscore.

2020-10-15 07:44 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/App.xaml.cs
> +            Container.Collection.Register(typeof(IViewModel<>), asm);
That's for the possible future needs, but I'll just remove it for now, so it won't confuse.

2020-10-15 07:50 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/AppShell.xaml.cs
> +            sPrinciplePage.Title = sPrinciplePage.ViewModel.Model.Title;
Yes, I've already made these bindings, but somehow forgot to remove these lines. Removed them.

2020-10-15 08:00 UTC, YuliaLoyko requested changes

2020-10-15 08:00 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/BasePrinciplePageViewModel.cs
> +        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
i'd move this one to a BaseViewModel (believe it'll be helpful for all viewModels)

2020-10-15 08:13 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Interfaces/IViewModel.cs
> +}
Checked. Configured

2020-10-15 08:15 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/BasePrinciplePageViewModel.cs
> +        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
Done it

2020-10-15 08:20 UTC, YuliaLoyko approved these changes

2020-10-15 08:29 UTC, merged