Shultsedu 261 add modal navigation
nadiiazhurba/Combined-Shell-TestProject pull request #4
Opened 2020-10-16 15:26 UTC by nadiiazhurba

2020-10-19 08:20 UTC, YuliaLoyko requested changes

2020-10-19 08:20 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/AppShell.xaml.cs
> +            Routing.RegisterRoute(RouteNames.LoginPage, typeof(LoginPage));
why do we need to configure Login and Registration pages in both Access and App Shell?

2020-10-19 08:20 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Helpers/RouteBuilder.cs
> +        public static string GoToMainPage(string username = "")
actually, i believe we should rethink naming here. Because GoToMainPage name does not represent actual function behavior

2020-10-19 08:20 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Helpers/RouteBuilder.cs
> +        public static string GoToMainPage(string username = "")
same for all other functions in this class

2020-10-19 08:20 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/LoadingPageViewModel.cs
> +                await routingService.NavigateTo($"///{RouteNames.MainPage}");
why won't we use route builder here?

2020-10-19 08:20 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/LoginPageViewModel.cs
> +            Shell.Current.GoToAsync(RouteBuilder.GoToRegistrationPage());
so try to use await with all async calls

2020-10-19 08:20 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Helpers/RouteBuilder.cs
> +            return $"///{RouteNames.MainPage}?{RouteNames.PrincipleInfoPageUsernameParam}={username}";
also regarding the way of passing params: i'm not sure it's going to work in more or less production apps, as we'll have to create new routes for each page
may be we can think about some object passing (eg something similar to NavigationParameters in prism?)

2020-10-19 08:20 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/LoadingPageViewModel.cs
> +                App.Current.MainPage = new AccessShell();
i'd say changing main page should go to routing service. it's better to avoid static setters in viewmodels

2020-10-19 08:20 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/LoginPageViewModel.cs
> +            Shell.Current.GoToAsync(RouteBuilder.GoToRegistrationPage());
also i'm a little bit confused about using both routingService.NavigateTo and Shell.Current.GoToAsync in the same viewmodel
let's make it more unified (eg use only routing service)

2020-10-19 08:20 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Views/LoadingPage.xaml.cs
> +            ViewModel = viewModel;
i assume we are going to set viewModel and BindingContext for every page
may be we can extract it to a base page?

2020-10-19 08:26 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/AppShell.xaml.cs
> +            Routing.RegisterRoute(RouteNames.LoginPage, typeof(LoginPage));
Because we need them for both shells. 

First use case is about entering the application using Modal views and after that user won't have possibility to return to this part. 
And second one is about logout functionality which includes entering these views in Modal mode from existing app Navigation flow. 

I could just move back to Access Shell on logout, but it's useful to learn that both ways of implementation work fine so i tried opening these pages from App Shell as well.

2020-10-19 08:30 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Helpers/RouteBuilder.cs
> +        public static string GoToMainPage(string username = "")
I think I know what you mean. I've also thought about naming them in other way, but decided that class name is already speaking for itself. 
But if you think of changing them, it's Ok for me, I'll change naming in next commit.

2020-10-19 08:36 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/LoadingPageViewModel.cs
> +                await routingService.NavigateTo($"///{RouteNames.MainPage}");
I thought about that. Currently we don't have user specified data on this step, but it won't hurt to create one, so I'll change it.

2020-10-19 08:40 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/LoginPageViewModel.cs
> +            Shell.Current.GoToAsync(RouteBuilder.GoToRegistrationPage());
I see, this one slipped from my sight, will fix it.

2020-10-19 09:00 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/LoadingPageViewModel.cs
> +                App.Current.MainPage = new AccessShell();
I see, changed it.

2020-10-19 09:11 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Helpers/RouteBuilder.cs
> +            return $"///{RouteNames.MainPage}?{RouteNames.PrincipleInfoPageUsernameParam}={username}";
Ok, working on it. Will be included in next commit.

2020-10-19 11:38 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/LoadingPage.xaml.cs
> +            ViewModel = viewModel;
I'm trying to find the best way possible to implement this, but I have some issues doing this. I will try implementing it further if it's convenient to spend time on this during this task implementation.

2020-10-20 07:32 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/LoadingPage.xaml.cs
> +            ViewModel = viewModel;
Done it with latest commit

2020-10-20 08:03 UTC, YuliaLoyko requested changes

2020-10-20 08:12 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Helpers/RouteBuilder.cs
> +        public static string GetDetailsPageRoute(NavigationParameters.NavigationParameters navigationParameters = null)
Changed

2020-10-20 08:12 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/DetailsPageViewModel.cs
> +        public string PrevTitle {
Done

2020-10-20 08:12 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/RegistrationPageViewModel.cs
> +            };
Done

2020-10-20 08:13 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Helpers/ViewModelFactory/ViewModelFactory.cs
> +            Add(name, typeof(T));
In order to save consistency with Dictionary implementation. This way suggested with official documentation as well

2020-10-20 08:14 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Interfaces/IViewModel.cs
> +        string ViewModelName { get; }
String? No, it was left for the future, but I deleted it just in case.

2020-10-20 08:17 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Helpers/ViewModelFactory/ViewModelFactory.cs
> +            Add(name, typeof(T));
so should this factory be a dictionary at all in such case?

2020-10-20 08:19 UTC, YuliaLoyko approved these changes

2020-10-20 08:19 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Helpers/RouteBuilder.cs
> +        public static string GetDetailsPageRoute(RouteNavigationParameters.NavigationParameters navigationParameters = null)
we can import namespace now instead of explicitly indicating it)

2020-10-20 08:36 UTC, merged