Shultsedu 271 list view
nadiiazhurba/Combined-Shell-TestProject pull request #5
Opened 2020-10-22 10:30 UTC by nadiiazhurba

2020-10-22 17:14 UTC, YuliaLoyko requested changes

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +            set => SetProperty(ref id, value);
ah, i see) you're already using it, cool!
so forget about my comment regarding SetProperty method
just consider using it everywhere instead of OnPropertyChanged

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +                SetProperty(ref contact,
i think we should extract deserialization to some base methods)

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +            return isValidDateOfBirth && isValidCountry;
may be let's create a kind of ValidationHelper?
it will keep the list of validatable objects from the app and run validation on them)

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +            return isValidDateOfBirth && isValidCountry;
and probably generate messages as well)

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +                {RouteNames.ContactParam, JsonConvert.SerializeObject(contact)}
should we serialize it here?

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +            var isValid = FirstName.Validate();
same thing regarding the validation here

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +            const string valMsg = "A First Name is required with 3 to 50 characters.";
let's create .resx file and keep strings there?

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNotesPageViewModel.cs
> +            await routingService.NavigateTo(RouteBuilder.GetContactsPage());
i supposed we will pass updated contact as a navigation parameter?

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/ExtendedBindableObject.cs
> +            }
let's add one empty line after closing curly bracket) and let's add this rule to a stylecop as well)

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Views/BasePage.cs
> +            ((BaseViewModel) ViewModel).Navigation = Navigation;
we should rethink this approach

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Views/EditContactBirthDateCountryPage.xaml
> +            <Label Text="Date of Birth"
let's extract all messages to .resx file)

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Views/EditContactNamePage.xaml
> +                    <behaviors:EventToCommandBehavior EventName="TextChanged"
👍

2020-10-22 17:14 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Views/EditContactNotesPage.xaml
> +            <Entry Text="{Binding Notes}"
let's use autoexpandable editor instead

2020-10-23 07:40 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.Android/MainActivity.cs
> -using Android.Views;
Yes, I agree. This has been done accidentally.

2020-10-23 07:43 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.Android/Resources/Resource.designer.cs
>  			public const int D = 2131165279;
Isn't it needed to follow also Resources changes?

2020-10-23 07:47 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.Android/SideMenuFlyoutShellTestProject.Android.csproj
> +    <AndroidResource Include="Resources\drawable\delete.png" />
That's because the topic that we discussed earlier. That it's not the part of tasks, because each time we'll have designer for these purposes. But I can if it's needed add all correct dimensions for both OS.

2020-10-23 07:48 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.iOS/SideMenuFlyoutShellTestProject.iOS.csproj
> +    <BundleResource Include="Resources\delete.png" />
Same as for the previous question)

2020-10-23 07:50 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/App.xaml.cs
> +            Container.Register(typeof(EditContactNamePage));
Because we go there using routing, so we don't need them registered in DI. And also that's what we discussed previously as well. That we shouldn't register things that we don't use in Container.

2020-10-23 07:59 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/AppShell.xaml.cs
> +            Routing.RegisterRoute(RouteNames.EditContactNamePage, typeof(EditContactNamePage));
It's an interesting suggestion. I thought that type of independent route names were suggested by documentation, so we can easily rename or replace Page with another one and this won't lead to changes in all of the places where the route is called. If we use nameof, we'll bind all other pages that call this one instead of abstraction making classes less independent from each other.

2020-10-23 08:03 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Behaviors/BindableBehavior.cs
> +    public class BindableBehavior<T> : Behavior<T> where T : BindableObject
Do you mean some readme.txt file with explanations of all reusable and public code?

2020-10-23 08:07 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Behaviors/BindableBehavior.cs
> +                BindingContext = visualElement.BindingContext;
Ok. If we have this kind of convention to add curly braces everywhere with 'if' I'll add now.

2020-10-23 08:18 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Behaviors/BindableBehavior.cs
> +                BindingContext = visualElement.BindingContext;
Done it

2020-10-23 08:20 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.Android/Resources/Resource.designer.cs
>  			public const int D = 2131165279;
I can if it's really needed.

2020-10-23 08:28 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject.Android/SideMenuFlyoutShellTestProject.Android.csproj
> +    <AndroidResource Include="Resources\drawable\delete.png" />
But I can spend some time on them if it's important. All of current icons need improvements and I can try to find correct resolutions and replace all of them.

2020-10-23 08:46 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Behaviors/EventToCommandBehavior.cs
> +            BindableProperty.CreateAttached("EventName", typeof(string), typeof(EventToCommandBehavior), null,
Good suggestion. Done it.

2020-10-23 08:49 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Behaviors/EventToCommandBehavior.cs
> +        protected Delegate _handler;
Done it already. It shouldn't be seen, I just thought I'll have time for clean-up yesterday before review.

2020-10-23 08:53 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Behaviors/EventToCommandBehavior.cs
> +                .GetRuntimeMethods().First(m => m.Name == "Invoke");
Yes, done it. It's also one of leftovers left for clean-up

2020-10-23 09:39 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Helpers/RouteBuilder.cs
> +        public static string GetEditContactNamePageRoute(RouteNavigationParameters.NavigationParameters navigationParameters = null)
After reading this suggestion, I'm thinking about if for some time now. Probably, I can unify this method and decide which route to take from RouteNames and whether to add navigation parameters right on the Page, before call of this method, but it seems like after that, these unified methods won't be needed, because main part of job would be done already on page (decide which RouteName, how to put them together and which Params to use). So this RouteBuilder will be redundant interlayer for some part of routings. I think that it can provide inconsistency in project. What you think about that?

2020-10-23 09:40 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validators/AgeValidationRule.cs
> +namespace SideMenuFlyoutShellTestProject.Validators
I see and agree with that. Done it.

2020-10-23 09:51 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validators/AgeValidationRule.cs
> +            return years >= 18;
Yes, it can be useful for the future. But it can complicate implementation, 'cause we should better use TimeSpan for more unified solution, because we can be connected not to years, but to days in the future tasks. Taking that into account I thought that all unifications would better be done after we get such necessity. But If we suggest, that DateTime validator with min and max TimeSpan values will be needed for some other screens, I can provide that improvements. 

Probably, if we need more unifications with validation, I can provide universal one also for Name and Notes, so we will pass min and max amount of symbols in string. And I'll use one Validator for both types of fields. 

But I have some doubts, because these unifications will bring us less amount of code, but can provide us with worse readability and less understanding of business logic from code for the future.

2020-10-23 09:53 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validators/AgeValidationRule.cs
> +            return years >= 18;
For now, just made improvement adding variable that will explain what is the number 18 means, so we wouldn't have magical number.

2020-10-23 09:54 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validators/IValidationRule.cs
> +        bool Check(T value);
Ok, renamed.

2020-10-23 10:05 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validators/IsNotNullOrEmptyRule.cs
> +    public class IsNotNullOrEmptyRule<T> : IValidationRule<T>
Nice suggestion. Nullable types are already supported, because firstly it check type for null value not depending on where it's string or not. But I also added check for IList types, because they can be with Count=0 and changed implementation a bit for the sake of universality.

2020-10-23 10:07 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validators/NameValidationRule.cs
> +            return value is string str && str.Length > 3 && str.Length < 50;
I see. That's what I suggested couple comments earlier. I also asked question there if this unification will be for good or  won't take into a count readability and better business logic understanding from code. Waiting for an answer there or here in comments

2020-10-23 10:09 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validators/NotesValidationRule.cs
> +    public class NotesValidationRule<T> : IValidationRule<T>
Yes. To be suggested under the previous comments.

2020-10-23 12:21 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validators/ValidatableObject.cs
> +                errors = value;
I know what you mean. Ok, I reused that part of code that I have in BaseVM putting it in ExtendedBindableObject and inheriting Base VM from it.

2020-10-23 12:22 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validators/ValidatableObject.cs
> +            var errs = validations.Where(v => !v.Check(Value))
Here I should specifically choose this name in order not to have conflicts with field on class level.

2020-10-23 12:23 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/BaseViewModel.cs
> +        public INavigation Navigation { get; set; }
In order to have possibility to perform Navigation in Modal Pages.

2020-10-23 12:26 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            MessagingCenter.Subscribe<EditContactNotesPageViewModel, Contact>(
I've just improved navigation a bit, so I can use simple NavigationParameters. Will be replaced in next commit.

2020-10-23 12:33 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +            set => SetProperty(ref id, value);
Yes)) I've just moved it on a higher level so I can use it everywhere)

2020-10-23 12:35 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            ((EditContactNamePageViewModel) editNamePage.BindingContext).ContactModel = new Contact();
Ok, sure. I'm ready to discuss. It was kind of tough to go to Modal Page with creation of it's own navigation inside, so I'll be glad to have more appropriate solution.

2020-10-23 12:36 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            MessagingCenter.Subscribe<EditContactNotesPageViewModel, Contact>(
Done it.

2020-10-23 12:40 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +                return new Command((e) =>
Yeap) Made clean-up to this file.

2020-10-23 13:00 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +                SetProperty(ref contact,
Setters can differ a little bit, but if it's needed, done it. Moved deserialization of Contact to EditContactBaseViewModel.

2020-10-23 13:03 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +            const string valMsg = "A First Name is required with 3 to 50 characters.";
I also thought about it and I would suggest to do it as a part of different task. For example, "Implement Localization". And make all additional changes for this? 
Or is it required as a part of this one?

2020-10-23 13:06 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +                {RouteNames.ContactParam, JsonConvert.SerializeObject(contact)}
Do you want to move it somewhere? It's definitely should be serialized right before sending and also it's not a part of RouteBuilder class. I can put it in base class, but which part would you think would be better? Just JsonConvert.SerializeObject(contact)? Or the whole creation of NavigationParameter for Contact?

2020-10-23 13:07 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +                {RouteNames.ContactParam, JsonConvert.SerializeObject(contact)}
Also I think that it's possible that we would need different NavigationParameters in some time for different Pages as we think about future extensions of app.

2020-10-23 13:08 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNotesPageViewModel.cs
> +            await routingService.NavigateTo(RouteBuilder.GetContactsPage());
Yes, done it as part of one of the previous comments changes.

2020-10-23 13:08 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ExtendedBindableObject.cs
> +            }
Done it

2020-10-23 13:09 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/BasePage.cs
> +            ((BaseViewModel) ViewModel).Navigation = Navigation;
Ok. Let's discuss it further. I would be glad if there is the easier and better way)

2020-10-23 13:11 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/EditContactBirthDateCountryPage.xaml
> +            <Label Text="Date of Birth"
Answered to same comment before. I think in order not to make this task even bigger and more complex, I'd suggest to do it as a complex refactoring for all text in project in the next task.

2020-10-23 13:13 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/EditContactNotesPage.xaml
> +            <Entry Text="{Binding Notes}"
Is it connected to creation of CustomRenderers? If it is, can we move with it to next task? It would be good to have it as a separate one, because it requires additional time and adds complexity. It would be also good because this PR is already too big to have a clear picture of changes.

2020-10-23 13:20 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBirthDateCountryPageViewModel.cs
> +            return isValidDateOfBirth && isValidCountry;
Interesting suggestion. Let's discuss it further. It is possible that at a time when there are a lot of ValidatableObjects this Helper would have too many data, on the other hand, it can store all the messages easily. I don't know, really, needs to be discussed.

2020-10-23 13:21 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +            var isValid = FirstName.Validate();
To be discussed as well))

2020-10-23 16:53 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/EditContactBirthDateCountryPage.xaml
> +            <Label Text="Date of Birth"
Since I've got time for this, I've tried to add resx file, but with no success currently. That's strange, because I've worked with it before successfully. Somehow in throws Compile error, that cannot find resource class, even though there are no issues in IDE shown. Trying to figure it out but with no result for now.

2020-10-23 17:02 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Views/EditContactBirthDateCountryPage.xaml
> +            <Label Text="Date of Birth"
Even setting PublicResXFileCodeGenerator didn't help

2020-10-26 07:52 UTC, YuliaLoyko requested changes

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/App.xaml.cs
> +            Container.Register(typeof(EditContactNamePage));
👍

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Behaviors/BindableBehavior.cs
> +    public class BindableBehavior<T> : Behavior<T> where T : BindableObject
no, i mean comments, eg

```
    /// <summary>
    /// Behavior class, responsible for ... 
    /// </summary>
```

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Behaviors/EventToCommandBehavior.cs
> +        public static readonly BindableProperty EventArgsConverterParameterProperty = BindableProperty.CreateAttached(nameof(EventArgsConverterParameter), typeof(object), typeof(EventToCommandBehavio
let's also try to avoid very long lines. it's usually 120 characters length max (and you can check your ide settings to at list show it)

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Helpers/RouteBuilder.cs
> +        public static string GetEditContactNamePageRoute(RouteNavigationParameters.NavigationParameters navigationParameters = null)
let's discuss

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/BaseViewModel.cs
> +        public INavigation Navigation { get; set; }
i'd prefer to extract it to a service

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactBaseViewModel.cs
> +                if (string.IsNullOrEmpty(value)) return;
braces

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +            const string valMsg = "A First Name is required with 3 to 50 characters.";
ok, let's do as a part of localization task
just wanted to note that we should avoid hardcoded strings in the app)

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Validation/NameValidationRule.cs
> +            return value is string str && str.Length > 3 && str.Length < 50;
it seems my other comments were lost during namespace rename
so i've suggested to use more general rules (rather than so concrete, like NameValidation, NotesValidation, etc)

for example here - we can use MinMaxLengthValidationRule instead (and configure min/max values). it can be reused for notes as well

same for date - it's better to configure min-max timespans instead of using hardcoded values

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +                if (string.IsNullOrEmpty(value)) return;
seems i've seen it in EditContactBaseViewModel.cs

2020-10-26 07:52 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            await Navigation.PushModalAsync(new NavigationPage(editNamePage));
seems my comments were lost here
so i'd assume we shouldn't resolve pages and set items here
all these actions should be done in navigation service

2020-10-26 08:33 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Behaviors/BindableBehavior.cs
> +    public class BindableBehavior<T> : Behavior<T> where T : BindableObject
Created comments for EventToCommandBehavior and BindableBehaviour

2020-10-26 08:45 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/BaseViewModel.cs
> +        public INavigation Navigation { get; set; }
Ok. I started investigating best solutions for moving it to service. Probably, we'll actually need new service for that. I'll leave it for implementation after status call.

2020-10-26 08:48 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +            const string valMsg = "A First Name is required with 3 to 50 characters.";
I totally agree with you and let's do it further. I know that this is a good practice to have all resources in special place, so we can add new localization easily and change strings correctly in the future.

2020-10-26 08:50 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Behaviors/EventToCommandBehavior.cs
> +        public static readonly BindableProperty EventArgsConverterParameterProperty = BindableProperty.CreateAttached(nameof(EventArgsConverterParameter), typeof(object), typeof(EventToCommandBehavio
No problem. Moved part of these lines to the next one.

2020-10-26 08:53 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validation/NameValidationRule.cs
> +            return value is string str && str.Length > 3 && str.Length < 50;
Yes, I saw suggestions and commented on them. So it's about practices that we use. It can be this way or the other. We should choose the place where this logic suits better. We can discuss in further in a call.

2020-10-26 08:54 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            await Navigation.PushModalAsync(new NavigationPage(editNamePage));
Your weren't lost, I saw them and answered. Maybe, all the discussion got lost

2020-10-26 08:55 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            await Navigation.PushModalAsync(new NavigationPage(editNamePage));
I'm considering creation special Navigation Service for that, because that's not a Shell usage or a routing anymore.

2020-10-26 09:46 UTC, YuliaLoyko approved these changes
will make changes in separate prs

2020-10-26 09:48 UTC, merged