Implemented NavigationService
nadiiazhurba/Combined-Shell-TestProject pull request #6
Opened 2020-10-26 15:08 UTC by nadiiazhurba

2020-10-27 07:36 UTC, YuliaLoyko requested changes

2020-10-27 07:36 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Helpers/NavigationContext.cs
> +        public static object GetParam(BindableObject view)
let's try to use full names, Parameter here

2020-10-27 07:36 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Services/NavigationService/INavigationService.cs
> +    public interface INavigationService
let's add doc comments to all interfaces

2020-10-27 07:36 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +
configure your ide to trim white spaces

2020-10-27 07:36 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            navigationService.Clear();
i'm a little bit confused with this clear call.. what is it for?

2020-10-27 07:36 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Services/NavigationService/INavigationService.cs
> +    public interface INavigationService
and interface methods)

2020-10-27 07:36 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Services/NavigationService/ViewNavigationService.cs
> +        public Page SetRootPage(string rootPageKey)
what is it supposed to be used for?
actually i'm not sure about naming, because we do not set page here, just create it?

2020-10-27 07:36 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Services/NavigationService/ViewNavigationService.cs
> +        public Page SetRootPage(string rootPageKey)
actually i have a lot of questions about methods here, so will wait until you add doc comments))

2020-10-27 08:40 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Helpers/NavigationContext.cs
> +        public static object GetParam(BindableObject view)
Done it

2020-10-27 09:05 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +
Done it

2020-10-27 09:06 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            navigationService.Clear();
It is needed because I use this Navigation type only once in this module, so it should be clear before starting a new Modal flow. If it's not, there are probably some leftovers in Navigation Stack there, that are not up to date.

2020-10-27 09:08 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Services/NavigationService/ViewNavigationService.cs
> +        public Page SetRootPage(string rootPageKey)
We actually kinda set it here. It is supposed to be used if some part of application or the whole app will be moved to work with this service, so it is way to set the RootPage for new NavigationPage in order to start new Navigation Stack.

2020-10-27 10:53 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Services/NavigationService/INavigationService.cs
> +    public interface INavigationService
Done it

2020-10-30 09:02 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Services/NavigationService/ViewNavigationService.cs
> +        public Page SetRootPage(string rootPageKey)
mmmm, not 100% agree. because people do not expect to receive Page response for Set method)

2020-10-30 09:07 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Services/NavigationService/ViewNavigationService.cs
> +        public Page SetRootPage(string rootPageKey)
I see, I'll try to change naming to a better one.

2020-10-30 09:11 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Services/NavigationService/ViewNavigationService.cs
> +        public Page SetRootPage(string rootPageKey)
Done it

2020-10-30 09:15 UTC, YuliaLoyko requested changes

2020-10-30 09:15 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            navigationService.Clear();
i'd say it's not straightforward enough.. in such case we should know inner navigation service implementation (know that it has some navigation stack, etc), which is not the best option
can we hide this clearing inside NavigateModalAsync itself?

2020-10-30 09:21 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/ContactsPageViewModel.cs
> +            navigationService.Clear();
Yes, we can. Done it

2020-10-30 09:39 UTC, YuliaLoyko approved these changes

2020-10-30 09:39 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Services/NavigationService/ViewNavigationService.cs
> +        private void Clear()
seems this one can be removed

2020-10-30 09:44 UTC, merged