Shultsedu 271 validation helper
nadiiazhurba/Combined-Shell-TestProject pull request #9
Opened 2020-10-27 20:47 UTC by nadiiazhurba

2020-10-28 08:05 UTC, YuliaLoyko requested changes

2020-10-28 08:05 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +        public ICommand ValidateLastNameCommand => new Command(() => LastName.Validate());
may it be written `new Command(LastName.Validate);`

2020-10-28 08:05 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/Validation/Base/ValidatableObject.cs
> +                    errors?.Aggregate((i, j) => i + "\n" + j) : string.Empty;
here and below please

2020-10-28 12:20 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/Validation/Base/ValidatableObject.cs
> +                    errors?.Aggregate((i, j) => i + "\n" + j) : string.Empty;
I see. Agree with you and will change it in following commit.

2020-10-28 12:25 UTC, nadiiazhurba commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +        public ICommand ValidateLastNameCommand => new Command(() => LastName.Validate());
It cannot, because this method signature doesn't meet requirements to be in Command constructor only by itself.

2020-10-30 09:17 UTC, YuliaLoyko approved these changes

2020-10-30 09:17 UTC, YuliaLoyko commented on SideMenuFlyoutShellTestProject/ViewModels/EditContactNamePageViewModel.cs
> +        public ICommand ValidateLastNameCommand => new Command(() => LastName.Validate());
ah, it returns bool, i see)

2020-10-30 09:18 UTC, YuliaLoyko approved these changes

2020-10-30 09:19 UTC, merged